sudo: false

addons:
    apt_packages:
        - lib32stdc++6

env:
  global:
    - INCLUDE=addons/sourcemod/scripting/include/
    - SCRIPTING=addons/sourcemod/scripting/
    - SOURCEMOD_MAJOR=1.7
    - SOURCEMOD_MINOR=1.7.3-git5258
    - SCRIPT=build-env/addons/sourcemod/scripting/compile.sh

before_install:
  - mkdir build-env

install:
  - cd build-env
  - wget http://www.sourcemod.net/smdrop/$SOURCEMOD_MAJOR/sourcemod-$SOURCEMOD_MINOR-linux.tar.gz
  - tar -xzvf sourcemod-$SOURCEMOD_MINOR-linux.tar.gz
  - wget https://github.com/whocodes/serversys/archive/master.zip
  - unzip master.zip
  - chmod -R 777 serversys-master
  - cp -rv serversys-master/. .
  - cd addons/sourcemod
  - wget https://github.com/bcserv/smlib/archive/master.zip
  - unzip master.zip
  - chmod -R 777 smlib-master
  - cp -rv smlib-master/. .
  - cd scripting/include
  - wget https://forums.alliedmods.net/attachment.php?attachmentid=119072 -O system2.inc
  - cd ../../../../../
  - find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
  - cp -rv $SCRIPTING/. build-env/addons/sourcemod/scripting/
  - cp -rv $INCLUDE/. build-env/addons/sourcemod/scripting/include/

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx $SCRIPT

script:
  - ./$SCRIPT

after_success:
  - mkdir addons/sourcemomd/plugins
  - cp -rv build-env/addons/sourcemod/scripting/compiled/. addons/sourcemod/plugins
  - find . -name "build-env" -delete
  - find . -type f -exec curl --user $FTPUSER:$FTPPASS --ftp-create-dirs -T {} ftp://$FTPPATH/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/{} \;
